POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "Hashiq",
    "email": "japu@hash.com",
    "password": "12345655"
}

###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "japu@hash.com",
    "password": "12345655"
}


###

GET http://localhost:8000/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1Y2ZlNGVmYTYyNGM3NzEyOWZjMmIiLCJpYXQiOjE2NzkyMDU1OTgsImV4cCI6MTY4MDUwMTU5OH0.Ez9fZOrefmGnZfHjFg2JVYUuzAxndtTk_uwK0WN68vE


