GET http://localhost:8000/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1Y2ZlNGVmYTYyNGM3NzEyOWZjMmIiLCJpYXQiOjE2NzkyMDY2ODAsImV4cCI6MTY4MDUwMjY4MH0.kJF2_yWUtjh0AYHWzKWJ4zHDleqrt888WJcKKD0w5c0

###
POST http://localhost:8000/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1Y2ZlNGVmYTYyNGM3NzEyOWZjMmIiLCJpYXQiOjE2NzkyMDY2ODAsImV4cCI6MTY4MDUwMjY4MH0.kJF2_yWUtjh0AYHWzKWJ4zHDleqrt888WJcKKD0w5c0

###
PATCH http://localhost:8000/order/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1Y2ZlNGVmYTYyNGM3NzEyOWZjMmIiLCJpYXQiOjE2NzkyMDY2ODAsImV4cCI6MTY4MDUwMjY4MH0.kJF2_yWUtjh0AYHWzKWJ4zHDleqrt888WJcKKD0w5c0
Content-Type: application/json

{
    "orderId": "6416a97bda5aa91d9277b251"
}

###
PATCH http://localhost:8000/order/6416a97bda5aa91d9277b251
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1Y2ZlNGVmYTYyNGM3NzEyOWZjMmIiLCJpYXQiOjE2NzkyMDY2ODAsImV4cCI6MTY4MDUwMjY4MH0.kJF2_yWUtjh0AYHWzKWJ4zHDleqrt888WJcKKD0w5c0
Content-Type: application/json

{
    "status": "SHIPPED"
}
