GET http://localhost:8000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1Y2ZlNGVmYTYyNGM3NzEyOWZjMmIiLCJlbWFpbCI6ImphcHVAaGFzaC5jb20iLCJuYW1lIjoiSGFzaGlxIiwidXNlclR5cGUiOiJBRE1JTiIsImlhdCI6MTY3OTE1MTE1NiwiZXhwIjoxNjgwNDQ3MTU2fQ.4yZGgiO3CqvSgB1uYUkicFHehKSMBxnrFxEPHV7JzAc